# Generated by Django 3.2.4 on 2021-07-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210629_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.course'),
        ),
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, default='AM-2021-7-R7U7QTIGO', max_length=6, null=True),
        ),
    ]
