# Generated by Django 3.2.4 on 2021-07-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210702_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, default='AM-2021-7-2YCQZWY8A', max_length=6, null=True),
        ),
    ]
