# Generated by Django 3.2.4 on 2021-07-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210703_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='faces/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, default='AM-2021-7-SKNL2DROC', max_length=6, null=True),
        ),
    ]
